
export const languages = {
  en: {
    code: 'en',
    name: 'English',
    flag: '🇺🇸',
    translations: {
      // Navigation
      home: 'Home',
      login: 'Login',
      register: 'Register',
      dashboard: 'Dashboard',
      inbox: 'Inbox',
      settings: 'Settings',
      logout: 'Logout',
      
      // Landing Page
      heroTitle: 'Anonymous Messages Made Simple',
      heroSubtitle: 'Receive honest feedback and messages anonymously with Wanz Req',
      getStarted: 'Get Started',
      learnMore: 'Learn More',
      
      // Features
      featuresTitle: 'Why Choose Wanz Req?',
      anonymousTitle: 'Anonymous Messages',
      anonymousDesc: 'Receive messages without revealing sender identity',
      trackingTitle: 'Message Tracking',
      trackingDesc: 'Track sender location, device info, and more with premium',
      secureTitle: 'Secure & Private',
      secureDesc: 'Your data is encrypted and secure',
      
      // Pricing
      pricingTitle: 'Choose Your Plan',
      freeTitle: 'Free',
      freeDesc: '10 message hits tracking',
      premiumTitle: 'Premium',
      premiumDesc: 'Unlimited tracking for 3 months',
      price: 'Rp 20,000',
      upgrade: 'Upgrade',
      
      // Auth
      loginTitle: 'Welcome Back',
      registerTitle: 'Create Account',
      username: 'Username',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      loginBtn: 'Sign In',
      registerBtn: 'Create Account',
      
      // Dashboard
      welcomeBack: 'Welcome back',
      yourLink: 'Your Request Link',
      copyLink: 'Copy Link',
      totalMessages: 'Total Messages',
      hitsRemaining: 'Hits Remaining',
      
      // Messages
      sendMessage: 'Send Message',
      messageTitle: 'Message Title',
      messageContent: 'Your message...',
      attachFile: 'Attach File',
      attachLink: 'Attach Link',
      send: 'Send',
      anonymous: 'Anonymous',
      
      // Settings
      profileSettings: 'Profile Settings',
      displayName: 'Display Name',
      profilePicture: 'Profile Picture',
      requestTitle: 'Request Title',
      save: 'Save Changes',
      
      // Status
      free: 'Free',
      premium: 'Premium',
      
      // Notifications
      messageSent: 'Message sent successfully!',
      linkCopied: 'Link copied to clipboard!',
      settingsSaved: 'Settings saved successfully!',
      upgradeSuccess: 'Upgraded to Premium successfully!',
      notImplemented: '🚧 This feature isn\'t implemented yet—but don\'t worry! You can request it in your next prompt! 🚀'
    }
  },
  id: {
    code: 'id',
    name: 'Bahasa Indonesia',
    flag: '🇮🇩',
    translations: {
      // Navigation
      home: 'Beranda',
      login: 'Masuk',
      register: 'Daftar',
      dashboard: 'Dashboard',
      inbox: 'Kotak Masuk',
      settings: 'Pengaturan',
      logout: 'Keluar',
      
      // Landing Page
      heroTitle: 'Pesan Anonim Jadi Mudah',
      heroSubtitle: 'Terima feedback dan pesan secara anonim dengan Wanz Req',
      getStarted: 'Mulai Sekarang',
      learnMore: 'Pelajari Lebih Lanjut',
      
      // Features
      featuresTitle: 'Mengapa Pilih Wanz Req?',
      anonymousTitle: 'Pesan Anonim',
      anonymousDesc: 'Terima pesan tanpa mengungkap identitas pengirim',
      trackingTitle: 'Pelacakan Pesan',
      trackingDesc: 'Lacak lokasi pengirim, info perangkat, dan lainnya dengan premium',
      secureTitle: 'Aman & Privat',
      secureDesc: 'Data Anda terenkripsi dan aman',
      
      // Pricing
      pricingTitle: 'Pilih Paket Anda',
      freeTitle: 'Gratis',
      freeDesc: '10 pelacakan hit pesan',
      premiumTitle: 'Premium',
      premiumDesc: 'Pelacakan unlimited selama 3 bulan',
      price: 'Rp 20.000',
      upgrade: 'Upgrade',
      
      // Auth
      loginTitle: 'Selamat Datang Kembali',
      registerTitle: 'Buat Akun',
      username: 'Username',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Konfirmasi Password',
      loginBtn: 'Masuk',
      registerBtn: 'Buat Akun',
      
      // Dashboard
      welcomeBack: 'Selamat datang kembali',
      yourLink: 'Link Request Anda',
      copyLink: 'Salin Link',
      totalMessages: 'Total Pesan',
      hitsRemaining: 'Hit Tersisa',
      
      // Messages
      sendMessage: 'Kirim Pesan',
      messageTitle: 'Judul Pesan',
      messageContent: 'Pesan Anda...',
      attachFile: 'Lampirkan File',
      attachLink: 'Lampirkan Link',
      send: 'Kirim',
      anonymous: 'Anonim',
      
      // Settings
      profileSettings: 'Pengaturan Profil',
      displayName: 'Nama Tampilan',
      profilePicture: 'Foto Profil',
      requestTitle: 'Judul Request',
      save: 'Simpan Perubahan',
      
      // Status
      free: 'Gratis',
      premium: 'Premium',
      
      // Notifications
      messageSent: 'Pesan berhasil dikirim!',
      linkCopied: 'Link berhasil disalin!',
      settingsSaved: 'Pengaturan berhasil disimpan!',
      upgradeSuccess: 'Berhasil upgrade ke Premium!',
      notImplemented: '🚧 Fitur ini belum diimplementasikan—tapi jangan khawatir! Anda bisa memintanya di prompt berikutnya! 🚀'
    }
  },
  es: {
    code: 'es',
    name: 'Español',
    flag: '🇪🇸',
    translations: {
      home: 'Inicio',
      login: 'Iniciar Sesión',
      register: 'Registrarse',
      dashboard: 'Panel',
      inbox: 'Bandeja',
      settings: 'Configuración',
      logout: 'Cerrar Sesión',
      heroTitle: 'Mensajes Anónimos Simplificados',
      heroSubtitle: 'Recibe comentarios y mensajes de forma anónima con Wanz Req',
      getStarted: 'Comenzar',
      learnMore: 'Saber Más',
      featuresTitle: '¿Por Qué Elegir Wanz Req?',
      anonymousTitle: 'Mensajes Anónimos',
      anonymousDesc: 'Recibe mensajes sin revelar la identidad del remitente',
      trackingTitle: 'Seguimiento de Mensajes',
      trackingDesc: 'Rastrea ubicación del remitente, info del dispositivo y más con premium',
      secureTitle: 'Seguro y Privado',
      secureDesc: 'Tus datos están encriptados y seguros',
      pricingTitle: 'Elige Tu Plan',
      freeTitle: 'Gratis',
      freeDesc: '10 seguimientos de hits de mensajes',
      premiumTitle: 'Premium',
      premiumDesc: 'Seguimiento ilimitado por 3 meses',
      price: 'Rp 20.000',
      upgrade: 'Actualizar',
      loginTitle: 'Bienvenido de Nuevo',
      registerTitle: 'Crear Cuenta',
      username: 'Usuario',
      email: 'Correo',
      password: 'Contraseña',
      confirmPassword: 'Confirmar Contraseña',
      loginBtn: 'Iniciar Sesión',
      registerBtn: 'Crear Cuenta',
      welcomeBack: 'Bienvenido de nuevo',
      yourLink: 'Tu Enlace de Solicitud',
      copyLink: 'Copiar Enlace',
      totalMessages: 'Mensajes Totales',
      hitsRemaining: 'Hits Restantes',
      sendMessage: 'Enviar Mensaje',
      messageTitle: 'Título del Mensaje',
      messageContent: 'Tu mensaje...',
      attachFile: 'Adjuntar Archivo',
      attachLink: 'Adjuntar Enlace',
      send: 'Enviar',
      anonymous: 'Anónimo',
      profileSettings: 'Configuración de Perfil',
      displayName: 'Nombre de Visualización',
      profilePicture: 'Foto de Perfil',
      requestTitle: 'Título de Solicitud',
      save: 'Guardar Cambios',
      free: 'Gratis',
      premium: 'Premium',
      messageSent: '¡Mensaje enviado exitosamente!',
      linkCopied: '¡Enlace copiado al portapapeles!',
      settingsSaved: '¡Configuración guardada exitosamente!',
      upgradeSuccess: '¡Actualizado a Premium exitosamente!',
      notImplemented: '🚧 ¡Esta función aún no está implementada, pero no te preocupes! ¡Puedes solicitarla en tu próximo prompt! 🚀'
    }
  },
  fr: {
    code: 'fr',
    name: 'Français',
    flag: '🇫🇷',
    translations: {
      home: 'Accueil',
      login: 'Connexion',
      register: 'S\'inscrire',
      dashboard: 'Tableau de Bord',
      inbox: 'Boîte de Réception',
      settings: 'Paramètres',
      logout: 'Déconnexion',
      heroTitle: 'Messages Anonymes Simplifiés',
      heroSubtitle: 'Recevez des commentaires et messages anonymement avec Wanz Req',
      getStarted: 'Commencer',
      learnMore: 'En Savoir Plus',
      featuresTitle: 'Pourquoi Choisir Wanz Req?',
      anonymousTitle: 'Messages Anonymes',
      anonymousDesc: 'Recevez des messages sans révéler l\'identité de l\'expéditeur',
      trackingTitle: 'Suivi des Messages',
      trackingDesc: 'Suivez la localisation de l\'expéditeur, les infos de l\'appareil et plus avec premium',
      secureTitle: 'Sécurisé et Privé',
      secureDesc: 'Vos données sont cryptées et sécurisées',
      pricingTitle: 'Choisissez Votre Plan',
      freeTitle: 'Gratuit',
      freeDesc: '10 suivis de hits de messages',
      premiumTitle: 'Premium',
      premiumDesc: 'Suivi illimité pendant 3 mois',
      price: 'Rp 20.000',
      upgrade: 'Mettre à Niveau',
      loginTitle: 'Bon Retour',
      registerTitle: 'Créer un Compte',
      username: 'Nom d\'utilisateur',
      email: 'Email',
      password: 'Mot de Passe',
      confirmPassword: 'Confirmer le Mot de Passe',
      loginBtn: 'Se Connecter',
      registerBtn: 'Créer un Compte',
      welcomeBack: 'Bon retour',
      yourLink: 'Votre Lien de Demande',
      copyLink: 'Copier le Lien',
      totalMessages: 'Messages Totaux',
      hitsRemaining: 'Hits Restants',
      sendMessage: 'Envoyer un Message',
      messageTitle: 'Titre du Message',
      messageContent: 'Votre message...',
      attachFile: 'Joindre un Fichier',
      attachLink: 'Joindre un Lien',
      send: 'Envoyer',
      anonymous: 'Anonyme',
      profileSettings: 'Paramètres de Profil',
      displayName: 'Nom d\'Affichage',
      profilePicture: 'Photo de Profil',
      requestTitle: 'Titre de Demande',
      save: 'Sauvegarder les Modifications',
      free: 'Gratuit',
      premium: 'Premium',
      messageSent: 'Message envoyé avec succès!',
      linkCopied: 'Lien copié dans le presse-papiers!',
      settingsSaved: 'Paramètres sauvegardés avec succès!',
      upgradeSuccess: 'Mis à niveau vers Premium avec succès!',
      notImplemented: '🚧 Cette fonctionnalité n\'est pas encore implémentée—mais ne vous inquiétez pas! Vous pouvez la demander dans votre prochain prompt! 🚀'
    }
  },
  de: {
    code: 'de',
    name: 'Deutsch',
    flag: '🇩🇪',
    translations: {
      home: 'Startseite',
      login: 'Anmelden',
      register: 'Registrieren',
      dashboard: 'Dashboard',
      inbox: 'Posteingang',
      settings: 'Einstellungen',
      logout: 'Abmelden',
      heroTitle: 'Anonyme Nachrichten Vereinfacht',
      heroSubtitle: 'Erhalten Sie ehrliches Feedback und Nachrichten anonym mit Wanz Req',
      getStarted: 'Loslegen',
      learnMore: 'Mehr Erfahren',
      featuresTitle: 'Warum Wanz Req Wählen?',
      anonymousTitle: 'Anonyme Nachrichten',
      anonymousDesc: 'Erhalten Sie Nachrichten ohne Preisgabe der Absenderidentität',
      trackingTitle: 'Nachrichten-Tracking',
      trackingDesc: 'Verfolgen Sie Absenderstandort, Geräteinformationen und mehr mit Premium',
      secureTitle: 'Sicher & Privat',
      secureDesc: 'Ihre Daten sind verschlüsselt und sicher',
      pricingTitle: 'Wählen Sie Ihren Plan',
      freeTitle: 'Kostenlos',
      freeDesc: '10 Nachrichten-Hit-Tracking',
      premiumTitle: 'Premium',
      premiumDesc: 'Unbegrenztes Tracking für 3 Monate',
      price: 'Rp 20.000',
      upgrade: 'Upgraden',
      loginTitle: 'Willkommen Zurück',
      registerTitle: 'Konto Erstellen',
      username: 'Benutzername',
      email: 'E-Mail',
      password: 'Passwort',
      confirmPassword: 'Passwort Bestätigen',
      loginBtn: 'Anmelden',
      registerBtn: 'Konto Erstellen',
      welcomeBack: 'Willkommen zurück',
      yourLink: 'Ihr Anfrage-Link',
      copyLink: 'Link Kopieren',
      totalMessages: 'Nachrichten Gesamt',
      hitsRemaining: 'Verbleibende Hits',
      sendMessage: 'Nachricht Senden',
      messageTitle: 'Nachrichtentitel',
      messageContent: 'Ihre Nachricht...',
      attachFile: 'Datei Anhängen',
      attachLink: 'Link Anhängen',
      send: 'Senden',
      anonymous: 'Anonym',
      profileSettings: 'Profil-Einstellungen',
      displayName: 'Anzeigename',
      profilePicture: 'Profilbild',
      requestTitle: 'Anfrage-Titel',
      save: 'Änderungen Speichern',
      free: 'Kostenlos',
      premium: 'Premium',
      messageSent: 'Nachricht erfolgreich gesendet!',
      linkCopied: 'Link in die Zwischenablage kopiert!',
      settingsSaved: 'Einstellungen erfolgreich gespeichert!',
      upgradeSuccess: 'Erfolgreich auf Premium aktualisiert!',
      notImplemented: '🚧 Diese Funktion ist noch nicht implementiert—aber keine Sorge! Sie können sie in Ihrem nächsten Prompt anfordern! 🚀'
    }
  },
  ja: {
    code: 'ja',
    name: '日本語',
    flag: '🇯🇵',
    translations: {
      home: 'ホーム',
      login: 'ログイン',
      register: '登録',
      dashboard: 'ダッシュボード',
      inbox: '受信箱',
      settings: '設定',
      logout: 'ログアウト',
      heroTitle: '匿名メッセージを簡単に',
      heroSubtitle: 'Wanz Reqで匿名でフィードバックやメッセージを受け取る',
      getStarted: '始める',
      learnMore: '詳細を見る',
      featuresTitle: 'なぜWanz Reqを選ぶのか？',
      anonymousTitle: '匿名メッセージ',
      anonymousDesc: '送信者の身元を明かすことなくメッセージを受信',
      trackingTitle: 'メッセージ追跡',
      trackingDesc: 'プレミアムで送信者の場所、デバイス情報などを追跡',
      secureTitle: '安全でプライベート',
      secureDesc: 'あなたのデータは暗号化され安全です',
      pricingTitle: 'プランを選択',
      freeTitle: '無料',
      freeDesc: '10メッセージヒット追跡',
      premiumTitle: 'プレミアム',
      premiumDesc: '3ヶ月間無制限追跡',
      price: 'Rp 20,000',
      upgrade: 'アップグレード',
      loginTitle: 'おかえりなさい',
      registerTitle: 'アカウント作成',
      username: 'ユーザー名',
      email: 'メール',
      password: 'パスワード',
      confirmPassword: 'パスワード確認',
      loginBtn: 'サインイン',
      registerBtn: 'アカウント作成',
      welcomeBack: 'おかえりなさい',
      yourLink: 'あなたのリクエストリンク',
      copyLink: 'リンクをコピー',
      totalMessages: 'メッセージ総数',
      hitsRemaining: '残りヒット数',
      sendMessage: 'メッセージを送信',
      messageTitle: 'メッセージタイトル',
      messageContent: 'あなたのメッセージ...',
      attachFile: 'ファイルを添付',
      attachLink: 'リンクを添付',
      send: '送信',
      anonymous: '匿名',
      profileSettings: 'プロフィール設定',
      displayName: '表示名',
      profilePicture: 'プロフィール画像',
      requestTitle: 'リクエストタイトル',
      save: '変更を保存',
      free: '無料',
      premium: 'プレミアム',
      messageSent: 'メッセージが正常に送信されました！',
      linkCopied: 'リンクがクリップボードにコピーされました！',
      settingsSaved: '設定が正常に保存されました！',
      upgradeSuccess: 'プレミアムへのアップグレードが成功しました！',
      notImplemented: '🚧 この機能はまだ実装されていません—でも心配しないでください！次のプロンプトでリクエストできます！🚀'
    }
  },
  zh: {
    code: 'zh',
    name: '中文',
    flag: '🇨🇳',
    translations: {
      home: '首页',
      login: '登录',
      register: '注册',
      dashboard: '仪表板',
      inbox: '收件箱',
      settings: '设置',
      logout: '登出',
      heroTitle: '匿名消息变简单',
      heroSubtitle: '使用Wanz Req匿名接收诚实反馈和消息',
      getStarted: '开始使用',
      learnMore: '了解更多',
      featuresTitle: '为什么选择Wanz Req？',
      anonymousTitle: '匿名消息',
      anonymousDesc: '接收消息而不透露发送者身份',
      trackingTitle: '消息追踪',
      trackingDesc: '使用高级版追踪发送者位置、设备信息等',
      secureTitle: '安全私密',
      secureDesc: '您的数据已加密且安全',
      pricingTitle: '选择您的计划',
      freeTitle: '免费',
      freeDesc: '10条消息点击追踪',
      premiumTitle: '高级版',
      premiumDesc: '3个月无限追踪',
      price: 'Rp 20,000',
      upgrade: '升级',
      loginTitle: '欢迎回来',
      registerTitle: '创建账户',
      username: '用户名',
      email: '邮箱',
      password: '密码',
      confirmPassword: '确认密码',
      loginBtn: '登录',
      registerBtn: '创建账户',
      welcomeBack: '欢迎回来',
      yourLink: '您的请求链接',
      copyLink: '复制链接',
      totalMessages: '消息总数',
      hitsRemaining: '剩余点击数',
      sendMessage: '发送消息',
      messageTitle: '消息标题',
      messageContent: '您的消息...',
      attachFile: '附加文件',
      attachLink: '附加链接',
      send: '发送',
      anonymous: '匿名',
      profileSettings: '个人资料设置',
      displayName: '显示名称',
      profilePicture: '头像',
      requestTitle: '请求标题',
      save: '保存更改',
      free: '免费',
      premium: '高级版',
      messageSent: '消息发送成功！',
      linkCopied: '链接已复制到剪贴板！',
      settingsSaved: '设置保存成功！',
      upgradeSuccess: '成功升级到高级版！',
      notImplemented: '🚧 此功能尚未实现—但别担心！您可以在下一个提示中请求它！🚀'
    }
  },
  ar: {
    code: 'ar',
    name: 'العربية',
    flag: '🇸🇦',
    translations: {
      home: 'الرئيسية',
      login: 'تسجيل الدخول',
      register: 'التسجيل',
      dashboard: 'لوحة التحكم',
      inbox: 'صندوق الوارد',
      settings: 'الإعدادات',
      logout: 'تسجيل الخروج',
      heroTitle: 'الرسائل المجهولة أصبحت بسيطة',
      heroSubtitle: 'استقبل التعليقات والرسائل بشكل مجهول مع Wanz Req',
      getStarted: 'ابدأ الآن',
      learnMore: 'اعرف المزيد',
      featuresTitle: 'لماذا تختار Wanz Req؟',
      anonymousTitle: 'رسائل مجهولة',
      anonymousDesc: 'استقبل الرسائل دون الكشف عن هوية المرسل',
      trackingTitle: 'تتبع الرسائل',
      trackingDesc: 'تتبع موقع المرسل ومعلومات الجهاز والمزيد مع النسخة المميزة',
      secureTitle: 'آمن وخاص',
      secureDesc: 'بياناتك مشفرة وآمنة',
      pricingTitle: 'اختر خطتك',
      freeTitle: 'مجاني',
      freeDesc: '10 تتبعات نقرات الرسائل',
      premiumTitle: 'مميز',
      premiumDesc: 'تتبع غير محدود لمدة 3 أشهر',
      price: 'Rp 20,000',
      upgrade: 'ترقية',
      loginTitle: 'مرحباً بعودتك',
      registerTitle: 'إنشاء حساب',
      username: 'اسم المستخدم',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      confirmPassword: 'تأكيد كلمة المرور',
      loginBtn: 'تسجيل الدخول',
      registerBtn: 'إنشاء حساب',
      welcomeBack: 'مرحباً بعودتك',
      yourLink: 'رابط طلبك',
      copyLink: 'نسخ الرابط',
      totalMessages: 'إجمالي الرسائل',
      hitsRemaining: 'النقرات المتبقية',
      sendMessage: 'إرسال رسالة',
      messageTitle: 'عنوان الرسالة',
      messageContent: 'رسالتك...',
      attachFile: 'إرفاق ملف',
      attachLink: 'إرفاق رابط',
      send: 'إرسال',
      anonymous: 'مجهول',
      profileSettings: 'إعدادات الملف الشخصي',
      displayName: 'اسم العرض',
      profilePicture: 'صورة الملف الشخصي',
      requestTitle: 'عنوان الطلب',
      save: 'حفظ التغييرات',
      free: 'مجاني',
      premium: 'مميز',
      messageSent: 'تم إرسال الرسالة بنجاح!',
      linkCopied: 'تم نسخ الرابط إلى الحافظة!',
      settingsSaved: 'تم حفظ الإعدادات بنجاح!',
      upgradeSuccess: 'تم الترقية إلى النسخة المميزة بنجاح!',
      notImplemented: '🚧 هذه الميزة لم يتم تنفيذها بعد—لكن لا تقلق! يمكنك طلبها في الموجه التالي! 🚀'
    }
  },
  ru: {
    code: 'ru',
    name: 'Русский',
    flag: '🇷🇺',
    translations: {
      home: 'Главная',
      login: 'Войти',
      register: 'Регистрация',
      dashboard: 'Панель',
      inbox: 'Входящие',
      settings: 'Настройки',
      logout: 'Выйти',
      heroTitle: 'Анонимные Сообщения Стали Простыми',
      heroSubtitle: 'Получайте честные отзывы и сообщения анонимно с Wanz Req',
      getStarted: 'Начать',
      learnMore: 'Узнать Больше',
      featuresTitle: 'Почему Выбрать Wanz Req?',
      anonymousTitle: 'Анонимные Сообщения',
      anonymousDesc: 'Получайте сообщения не раскрывая личность отправителя',
      trackingTitle: 'Отслеживание Сообщений',
      trackingDesc: 'Отслеживайте местоположение отправителя, информацию об устройстве и многое другое с премиум',
      secureTitle: 'Безопасно и Приватно',
      secureDesc: 'Ваши данные зашифрованы и безопасны',
      pricingTitle: 'Выберите Ваш План',
      freeTitle: 'Бесплатно',
      freeDesc: '10 отслеживаний кликов сообщений',
      premiumTitle: 'Премиум',
      premiumDesc: 'Неограниченное отслеживание на 3 месяца',
      price: 'Rp 20,000',
      upgrade: 'Обновить',
      loginTitle: 'Добро Пожаловать Обратно',
      registerTitle: 'Создать Аккаунт',
      username: 'Имя Пользователя',
      email: 'Email',
      password: 'Пароль',
      confirmPassword: 'Подтвердить Пароль',
      loginBtn: 'Войти',
      registerBtn: 'Создать Аккаунт',
      welcomeBack: 'Добро пожаловать обратно',
      yourLink: 'Ваша Ссылка Запроса',
      copyLink: 'Копировать Ссылку',
      totalMessages: 'Всего Сообщений',
      hitsRemaining: 'Кликов Осталось',
      sendMessage: 'Отправить Сообщение',
      messageTitle: 'Заголовок Сообщения',
      messageContent: 'Ваше сообщение...',
      attachFile: 'Прикрепить Файл',
      attachLink: 'Прикрепить Ссылку',
      send: 'Отправить',
      anonymous: 'Анонимно',
      profileSettings: 'Настройки Профиля',
      displayName: 'Отображаемое Имя',
      profilePicture: 'Фото Профиля',
      requestTitle: 'Заголовок Запроса',
      save: 'Сохранить Изменения',
      free: 'Бесплатно',
      premium: 'Премиум',
      messageSent: 'Сообщение успешно отправлено!',
      linkCopied: 'Ссылка скопирована в буфер обмена!',
      settingsSaved: 'Настройки успешно сохранены!',
      upgradeSuccess: 'Успешно обновлено до Премиум!',
      notImplemented: '🚧 Эта функция еще не реализована—но не волнуйтесь! Вы можете запросить ее в следующем запросе! 🚀'
    }
  },
  pt: {
    code: 'pt',
    name: 'Português',
    flag: '🇧🇷',
    translations: {
      home: 'Início',
      login: 'Entrar',
      register: 'Registrar',
      dashboard: 'Painel',
      inbox: 'Caixa de Entrada',
      settings: 'Configurações',
      logout: 'Sair',
      heroTitle: 'Mensagens Anônimas Simplificadas',
      heroSubtitle: 'Receba feedback e mensagens honestas anonimamente com Wanz Req',
      getStarted: 'Começar',
      learnMore: 'Saiba Mais',
      featuresTitle: 'Por Que Escolher Wanz Req?',
      anonymousTitle: 'Mensagens Anônimas',
      anonymousDesc: 'Receba mensagens sem revelar a identidade do remetente',
      trackingTitle: 'Rastreamento de Mensagens',
      trackingDesc: 'Rastreie localização do remetente, informações do dispositivo e mais com premium',
      secureTitle: 'Seguro e Privado',
      secureDesc: 'Seus dados são criptografados e seguros',
      pricingTitle: 'Escolha Seu Plano',
      freeTitle: 'Grátis',
      freeDesc: '10 rastreamentos de cliques de mensagens',
      premiumTitle: 'Premium',
      premiumDesc: 'Rastreamento ilimitado por 3 meses',
      price: 'Rp 20.000',
      upgrade: 'Atualizar',
      loginTitle: 'Bem-vindo de Volta',
      registerTitle: 'Criar Conta',
      username: 'Nome de Usuário',
      email: 'Email',
      password: 'Senha',
      confirmPassword: 'Confirmar Senha',
      loginBtn: 'Entrar',
      registerBtn: 'Criar Conta',
      welcomeBack: 'Bem-vindo de volta',
      yourLink: 'Seu Link de Solicitação',
      copyLink: 'Copiar Link',
      totalMessages: 'Total de Mensagens',
      hitsRemaining: 'Cliques Restantes',
      sendMessage: 'Enviar Mensagem',
      messageTitle: 'Título da Mensagem',
      messageContent: 'Sua mensagem...',
      attachFile: 'Anexar Arquivo',
      attachLink: 'Anexar Link',
      send: 'Enviar',
      anonymous: 'Anônimo',
      profileSettings: 'Configurações de Perfil',
      displayName: 'Nome de Exibição',
      profilePicture: 'Foto de Perfil',
      requestTitle: 'Título da Solicitação',
      save: 'Salvar Alterações',
      free: 'Grátis',
      premium: 'Premium',
      messageSent: 'Mensagem enviada com sucesso!',
      linkCopied: 'Link copiado para a área de transferência!',
      settingsSaved: 'Configurações salvas com sucesso!',
      upgradeSuccess: 'Atualizado para Premium com sucesso!',
      notImplemented: '🚧 Este recurso ainda não foi implementado—mas não se preocupe! Você pode solicitá-lo no seu próximo prompt! 🚀'
    }
  }
};

export const getLanguageByCode = (code) => {
  return languages[code] || languages.en;
};

export const getAllLanguages = () => {
  return Object.values(languages);
};
